### ISSUE TITLE
Rearrange Notebooks

### ISSUE THREAD

**Issue by jannesgg** [ocean-data-factory-sweden/koster_yolov4#397]
It seems like a good time to revisit the structure of the notebooks as they currently are. Aspects such as the numbering don't really make sense anymore and we should try to group notebooks with similar functionality together in a better way (e.g. 3, 4).

The suggested structure would be something along the following lines:

| Old Number | New Designation | Comments |
|------------|------------|----------|
| 1        | Removed        | Project administration should take place in another way (see cdn-projects)  |
| 2        | Removed        | Replaced by Cloudina upload or uploading to a bucket or just having files locally  |
| 3, 4, 8        | Classify        | Zooniverse-specific notebooks should be grouped  |
| 5, 6       | Analyse        | ML training and evaluation  |
| 7, 9      | Publish        | Publish models and observations  |

**Comment by jannesgg** [comment]
Any thoughts on this @victor-wildlife?

**Comment by victor-wildlife** [comment]
@jannesgg it makes sense to rename them and get rid of the numbering. I would suggest the following grouping and naming:

Old Number | New Designation | Comments
-- | -- | --
1 | Removed | Project administration should take place in another way (see cdn-projects)
2 | Removed | Replaced by Cloudina upload or uploading to a bucket or just having files locally
3, 4, 8 | Manual Annotations | Zooniverse-specific notebooks should be grouped
9 | ML Annotations | Publish observations
5, 6, 7 | ML Training | ML training, evaluation and publishing of the models


Open to suggestions from the rest of the team. Also, we should think of a tutorial or platform in the manual annotations category that doesn't use Zooniverse (it will take us time though).

**Comment by jannesgg** [comment]
@victor-wildlife Cool, let's take this during our meeting on Thursday then :)
