### ISSUE TITLE
Mlflow permission issues when trying to run ML on template

### ISSUE THREAD

**Issue by victor-wildlife** [ocean-data-factory-sweden/koster_yolov4#417]
When trying to run the detect_yolo function in the publish observations notebook I get the following error
![Image](https://github.com/ocean-data-factory-sweden/kso/assets/55268669/88f21797-f170-4dc8-a4d8-e7e98c034627)
Is this because the mlflow is still down?

**Comment by jannesgg** [comment]
Should be fixed in latest dev, was due to mlflow being down. Closing for now.
